# Generated by Django 5.1.6 on 2025-03-05 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
