# Generated by Django 5.1.6 on 2025-03-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_softwareversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlink',
            name='filename',
        ),
    ]
